[package]
name = "tranquility_stager"
version = "0.1.0"
edition = "2018"

[dependencies]
aes = "0.7.4"
block-modes = "0.8.1"
flate2 = "1.0.22"
winapi = { version="0.3.9", features=["memoryapi"] }
reqwest = { version = "0.11", features = ["blocking"] }
hex = "0.4"
