[package]
name = "tranquility_stager"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "3.1.6"
aes = "0.7.4"
block-modes = "0.8.1"
flate2 = "1.0.22"
winapi = "0.3.9"
ntapi = "0.4.1"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }